# Question 1

In [2]:
import numpy as np

array=np.arange(2,50,3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [3]:
list1=[]
list2=[]

for i in range(5):
    list1.append(int(input()))
for i in range(5):
    list2.append(int(input()))

arr1=np.array(list1)
arr2=np.array(list2)

con_array=np.concatenate((arr1, arr2))
print(con_array)

sortarr=np.sort(con_array)
print(sortarr)

1
0
9
2
8
3
4
7
6
5
[1 0 9 2 8 3 4 7 6 5]
[0 1 2 3 4 5 6 7 8 9]


# Question 3

In [7]:
arr=np.array([[1,2,3],[1,2,5]])
print(arr.ndim)
print(arr.size)

2
6


# Question 4

In [8]:
arr = np.arange(10)
print("\nShape of Array :",arr.shape)

row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",row_arr.shape)

col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",col_arr.shape)


Shape of Array : (10,)

Shape of 2d Array in row major : (1, 10)

Shape of 2d Array in column major : (10, 1)


In [9]:
arr = np.arange(10)
print("\nShape of Array :",arr.shape)


row_arr = np.expand_dims(arr, axis=0)
print("\nShape of 2d Array in row major :",row_arr.shape)


col_arr = np.expand_dims(arr, axis=1)
print("\nShape of 2d Array in column major :",col_arr.shape)


Shape of Array : (10,)

Shape of 2d Array in row major : (1, 10)

Shape of 2d Array in column major : (10, 1)


# Question 5

In [10]:
arr_1 = np.square([1, 2, 3, 4, 5])
arr_2 = np.square([6, 7, 8, 9, 10])

print("\nHorizontal Append :", np.hstack((arr_1, arr_2)))
print("\nVertical Append :", np.vstack((arr_1, arr_2)))


Horizontal Append : [  1   4   9  16  25  36  49  64  81 100]

Vertical Append : [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


# Question 6

In [11]:
arr_1 = np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 10])

unique, counts = np.unique(arr_1, return_counts=True)
 
arr = np.asarray((unique, counts)).T

print(arr)

[[ 1  2]
 [ 2  2]
 [ 3  1]
 [ 4  2]
 [ 5  2]
 [ 6  1]
 [ 7  1]
 [ 8  1]
 [ 9  1]
 [10  1]
 [16  1]
 [25  1]]
